version: "3.7"
services:
  geocoding:
    environment:
      DEBUG: "True"
      ENABLE_FAKE_GEOCODER: "True"
      DB: "${DISEASE_NAME}"
  mongo:
    volumes:
      - "../verification/scripts:/verification/scripts"
  curator:
    command: "npm run dev"
    volumes:
      - "../verification/curator-service/api/src:/usr/src/app/verification/curator-service/api/src"
      - "../verification/curator-service/api/openapi:/usr/src/app/verification/curator-service/api/openapi"
    environment:
      LOCALSTACK_URL: "http://localstack:4566"
      SERVICE_ENV: "locale2e"
      AFTER_LOGIN_REDIRECT_URL: "http://localhost:3002"
      EVENT_ROLE_ARN: "fake"
      JOB_QUEUE_ARN: "fake"
      SESSION_COOKIE_KEY: "fake"
      STATIC_DIR: ""
      ENABLE_LOCAL_AUTH: "true"
      DISEASE_NAME: "${DISEASE_NAME}"
      BASE_URL: "${BASE_URL}"
      COMPLETE_DATA_BUCKET: "${COMPLETE_DATA_BUCKET}"
      DATA_DOWNLOAD_BUCKET: "${DATA_DOWNLOAD_BUCKET}"
      COUNTRY_DATA_BUCKET: "${COUNTRY_DATA_BUCKET}"
      REACT_APP_RECAPTCHA_SITE_KEY: "${VITE_APP_RECAPTCHA_SITE_KEY}"
      NODE_ENV: "dev"
  data:
    command: "npm run dev"
    volumes:
      - "../data-serving/data-service/src:/usr/src/app/data-serving/data-service/src"
      - "../data-serving/data-service/api:/usr/src/app/data-serving/data-service/api"
    depends_on:
      - mongo
    environment:
      SERVICE_ENV: "local"
      NODE_ENV: "dev"
  curatorui:
    command: "npm run start-noenv"
    volumes:
      - "../verification/curator-service/ui/src:/usr/src/app/verification/curator-service/ui/src"
    environment:
      # We can't use curator:3001 here because that's an internal DNS,
      # not accessible from the user's browser.
      # In production simply /auth/google would work.
      VITE_APP_LOGIN_URL: "http://localhost:3001/auth/google"
      VITE_APP_PUBLIC_MAPBOX_TOKEN: "${VITE_APP_PUBLIC_MAPBOX_TOKEN}"
      VITE_APP_POLICY_PUBLIC_ID: "${VITE_APP_POLICY_PUBLIC_ID}"
      VITE_APP_COOKIE_CONSENT_PUBLIC_ID: "${VITE_APP_COOKIE_CONSENT_PUBLIC_ID}"
      VITE_APP_RECAPTCHA_SITE_KEY: "${VITE_APP_RECAPTCHA_SITE_KEY}"
      VITE_APP_DATA_DICTIONARY_LINK: "${VITE_APP_DATA_DICTIONARY_LINK}"
      ENABLE_LOCAL_AUTH: "true"
      DISEASE_NAME: "${DISEASE_NAME}"
  localstack:
    image: localstack/localstack-pro
    ports:
      - "53:53"
      - "443:443"
      - "4510:4510"
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      LOCALSTACK_API_KEY: "${LOCALSTACK_API_KEY}"
      SERVICES: s3,ec2,ses,batch,events,iam,ecr
      DEBUG: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  setup-localstack:
    build:
      context: ./
    depends_on:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_ENDPOINT: "http://localstack:4566"
      DATA_BUCKET_NAME: "covid-19-data-export"
      CACHE_BUCKET_NAME: "covid-19-country-export"
      RETRIEVAL_BUCKET_NAME: "gdh-sources"
      SES_EMAIL_ADDRESS: "info@global.health"
